[package]
name = "guessing_game"
version = "0.1.0"
authors = ["wangs1203 <15201670063@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"